---
name: 'Deploy to Arc XP'
description: 'This is an action which makes it convenient to deploy to Arc XP'
author: 'Arc XP'
branding:
  icon: 'truck'
  color: 'blue'
runs:
  using: node20
  main: dist/index.cjs
inputs:
  # Stuff we need for this action
  org-id:
    description: 'The organization ID for the Arc XP organization'
    required: true
  api-key:
    description: 'The API key for Arc XP organization'
    required: true
  api-hostname:
    description: 'The API hostname for Arc XP organization'
    required: true
  bundle-prefix:
    description: 'The prefix for the bundle name, which is used to identify the bundle in the Arc XP UI'
    required: true
  artifact:
    description: 'The artifact to be uploaded to Arc XP Fusion'
    required: true
    default: 'dist/fusion-bundle.zip'
  retry-count:
    description: 'The number of times to retry the deployment if it fails'
    required: true
    default: 10
  retry-delay:
    description: 'The number of seconds to wait between retries'
    required: true
    default: 5
  minimum-running-versions:
    description: The minimum number of versions to keep in a "deployed" state at any given time. The maximum is 10, the minimum is 1.
    required: true
    default: 7
